template:
  - sensor:
      - name: 24h volume (main wallet ETH)
        state: "{{ state_attr('sensor.cryptoinfo_main_wallet_ethereum_eur', '24h_volume') | float(0) | round(0) }}"
        unit_of_measurement: "€"

      - name: Bitcoin owned
        state: >-
          {% if not is_state('sensor.cryptoinfo_bitcoin_usd', 'unknown') %}
            {{ (states('sensor.cryptoinfo_bitcoin_usd') | float(0) * 0.12345) | round(2) }}
          {% endif %}
        unit_of_measurement: "$"

      - name: Total my crypto
        unique_id: crypto_total
        state: >
          {{ integration_entities('cryptoinfo')
             | map('states')
             | map('float', 0)
             | sum
             | round(2) }}
        unit_of_measurement: >
          {{ expand(integration_entities('cryptoinfo'))
             | map(attribute='attributes.unit_of_measurement')
             | list
             | default(['$'], true)
             | first }}
